source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Auth'

pod 'FBSDKLoginKit'
pod 'GoogleSignIn'

# pod 'AFNetworking', '~> 3.0.4'
# pod 'youtube-ios-player-helper', '~> 0.1.4'
# pod 'MBProgressHUD', '~> 0.9.2'
# pod 'Flurry-iOS-SDK/FlurrySDK', '~> 7.1.0'
# pod 'OpenInGoogleMaps'
